# permissions for end users to edit files.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: file-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: maintain-files-operator
    app.kubernetes.io/part-of: maintain-files-operator
    app.kubernetes.io/managed-by: kustomize
  name: file-editor-role
rules:
- apiGroups:
  - file.example.com
  resources:
  - files
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - file.example.com
  resources:
  - files/status
  verbs:
  - get
